version: '3'

services:
  mysql-docker-container:
    image: mysql/mysql-server:latest
#    image: mysql:5.7.22
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_HOST=%
    volumes:
      - /data/mysql
  myredis:
    image: redis
    ports:
      - 6379:6379

  my-first-docker:
    restart: on-failure
    image: mhmhfalcon
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
      - myredis
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - /data/mhmhfalcon
#    networks:
#      - db-mongo-net1
#
#
#networks:
#  db-mongo-net1:
#    external:
#      name: br0
