spring.datasource:
  #url: "jdbc:mysql://localhost:3306/test"
  #url: "jdbc:mysql://172.17.0.2:3306/test"
  url: "jdbc:mysql://mysql-docker-container:3306/test"
  #driver-class-name=com.mysql.jdbc.Driver
  username: root
  password: "123456"
  #data: "classpath*:data.sql"
#spring.jpa:
#spring.h2.console.enabled: true

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.howtodoinjava: DEBUG
#    org.hibernate: TRACE

#
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.howtodoinjava: ERROR
#    org.hibernate: ERROR

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
          hibernate:
            show_sql: true
    generate-ddl: true
            #dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 8081

#
#server:
#  port: 9010
#  servlet:
#    context-path: /v3

